package com.proyectogrado.sgpa.model;

public enum SubcategoriaProducto {
    NUEVO_CONOCIMIENTO,
    DESARROLLO_TECNOLOGICO,
    APROPIACION_SOCIAL,
    DIVULGACION_PUBLICA_CIENCIA,
    FORMACION_RECURSO_HUMANO,
    MATERIAL_DIDACTICO,
    ACTIVIDAD_DOCENTE,
    GESTION_ACADEMICA,
    EXTENSION
}
