spring.application.name=sgpa

spring.datasource.url=jdbc:postgresql://localhost:5432/sgpa
spring.datasource.username=postgres
spring.datasource.password=udc

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect